version: '2.1'
services:
  app:
    build: .
    environment:
      MYAPP_DATABASE_HOST: db
      MYAPP_WEB_PORT: 8080
      MYAPP_CACHE_HOST:cache
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - 3000:8080
  db:
    image: healthcheck/redis:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myapp
